/** @type {import('tailwindcss').Config} */
module.exports = {
  content: [
    './src/pages/**/*.{js,ts,jsx,tsx,mdx}',
    './src/components/**/*.{js,ts,jsx,tsx,mdx}',
    './src/app/**/*.{js,ts,jsx,tsx,mdx}',
    './src/lib/**/*.{js,ts,jsx,tsx,mdx}',
  ],
  darkMode: 'class',
  theme: {
    extend: {
      colors: {
        // AuraAI brand colors
        primary: {
          DEFAULT: 'hsl(var(--primary))',
          50: 'hsl(210, 100%, 98%)',
          100: 'hsl(210, 100%, 96%)',
          200: 'hsl(210, 100%, 92%)',
          300: 'hsl(210, 100%, 84%)',
          400: 'hsl(210, 100%, 72%)',
          500: 'hsl(210, 100%, 60%)',
          600: 'hsl(210, 100%, 50%)',
          700: 'hsl(210, 100%, 40%)',
          800: 'hsl(210, 100%, 30%)',
          900: 'hsl(210, 100%, 20%)',
          950: 'hsl(210, 100%, 10%)',
        },
        'primary-foreground': 'hsl(var(--primary-foreground))',
        secondary: {
          DEFAULT: 'hsl(var(--secondary))',
          50: 'hsl(280, 100%, 98%)',
          100: 'hsl(280, 100%, 96%)',
          200: 'hsl(280, 100%, 92%)',
          300: 'hsl(280, 100%, 84%)',
          400: 'hsl(280, 100%, 72%)',
          500: 'hsl(280, 100%, 60%)',
          600: 'hsl(280, 100%, 50%)',
          700: 'hsl(280, 100%, 40%)',
          800: 'hsl(280, 100%, 30%)',
          900: 'hsl(280, 100%, 20%)',
          950: 'hsl(280, 100%, 10%)',
        },
        'secondary-foreground': 'hsl(var(--secondary-foreground))',
        accent: {
          DEFAULT: 'hsl(var(--accent))',
          50: 'hsl(45, 100%, 98%)',
          100: 'hsl(45, 100%, 96%)',
          200: 'hsl(45, 100%, 92%)',
          300: 'hsl(45, 100%, 84%)',
          400: 'hsl(45, 100%, 72%)',
          500: 'hsl(45, 100%, 60%)',
          600: 'hsl(45, 100%, 50%)',
          700: 'hsl(45, 100%, 40%)',
          800: 'hsl(45, 100%, 30%)',
          900: 'hsl(45, 100%, 20%)',
          950: 'hsl(45, 100%, 10%)',
        },
        'accent-foreground': 'hsl(var(--accent-foreground))',
        // UI colors
        background: 'hsl(var(--background))',
        foreground: 'hsl(var(--foreground))',
        card: {
          DEFAULT: 'hsl(var(--card))',
          foreground: 'hsl(var(--card-foreground))',
        },
        popover: {
          DEFAULT: 'hsl(var(--popover))',
          foreground: 'hsl(var(--popover-foreground))',
        },
        muted: {
          DEFAULT: 'hsl(var(--muted))',
          foreground: 'hsl(var(--muted-foreground))',
        },
        border: 'hsl(var(--border))',
        input: 'hsl(var(--input))',
        ring: 'hsl(var(--ring))',
        destructive: {
          DEFAULT: 'hsl(var(--destructive))',
          foreground: 'hsl(var(--destructive-foreground))',
        },
      },
      fontFamily: {
        sans: ['var(--font-sans)', 'Inter', 'system-ui', 'sans-serif'],
        display: ['var(--font-display)', 'Inter', 'system-ui', 'sans-serif'],
        mono: ['var(--font-mono)', 'JetBrains Mono', 'monospace'],
      },
      fontSize: {
        'xs': ['0.75rem', { lineHeight: '1rem' }],
        'sm': ['0.875rem', { lineHeight: '1.25rem' }],
        'base': ['1rem', { lineHeight: '1.5rem' }],
        'lg': ['1.125rem', { lineHeight: '1.75rem' }],
        'xl': ['1.25rem', { lineHeight: '1.75rem' }],
        '2xl': ['1.5rem', { lineHeight: '2rem' }],
        '3xl': ['1.875rem', { lineHeight: '2.25rem' }],
        '4xl': ['2.25rem', { lineHeight: '2.5rem' }],
        '5xl': ['3rem', { lineHeight: '1' }],
        '6xl': ['3.75rem', { lineHeight: '1' }],
        '7xl': ['4.5rem', { lineHeight: '1' }],
        '8xl': ['6rem', { lineHeight: '1' }],
        '9xl': ['8rem', { lineHeight: '1' }],
      },
      spacing: {
        '18': '4.5rem',
        '88': '22rem',
        '128': '32rem',
        '144': '36rem',
      },
      borderRadius: {
        'lg': 'var(--radius)',
        'md': 'calc(var(--radius) - 2px)',
        'sm': 'calc(var(--radius) - 4px)',
      },
      animation: {
        'fade-in': 'fadeIn 0.5s ease-in-out',
        'fade-out': 'fadeOut 0.5s ease-in-out',
        'slide-in-from-top': 'slideInFromTop 0.3s ease-out',
        'slide-in-from-bottom': 'slideInFromBottom 0.3s ease-out',
        'slide-in-from-left': 'slideInFromLeft 0.3s ease-out',
        'slide-in-from-right': 'slideInFromRight 0.3s ease-out',
        'scale-in': 'scaleIn 0.2s ease-out',
        'scale-out': 'scaleOut 0.2s ease-out',
        'bounce-in': 'bounceIn 0.6s ease-out',
        'pulse-slow': 'pulse 3s cubic-bezier(0.4, 0, 0.6, 1) infinite',
        'float': 'float 3s ease-in-out infinite',
        'glow': 'glow 2s ease-in-out infinite alternate',
        'shimmer': 'shimmer 2s linear infinite',
        'gradient': 'gradient 3s ease infinite',
        'spin-slow': 'spin 3s linear infinite',
        'wiggle': 'wiggle 1s ease-in-out infinite',
        'heartbeat': 'heartbeat 1.5s ease-in-out infinite',
        'rubber-band': 'rubberBand 1s ease-in-out',
        'shake': 'shake 0.5s ease-in-out',
        'tada': 'tada 1s ease-in-out',
        'wobble': 'wobble 1s ease-in-out',
        'jello': 'jello 1s ease-in-out',
        'hinge': 'hinge 2s ease-in-out',
        'roll-in': 'rollIn 1s ease-in-out',
        'roll-out': 'rollOut 1s ease-in-out',
        'zoom-in': 'zoomIn 0.3s ease-out',
        'zoom-out': 'zoomOut 0.3s ease-out',
        'flip-in-x': 'flipInX 0.6s ease-out',
        'flip-in-y': 'flipInY 0.6s ease-out',
        'flip-out-x': 'flipOutX 0.6s ease-out',
        'flip-out-y': 'flipOutY 0.6s ease-out',
        'light-speed-in': 'lightSpeedIn 0.5s ease-out',
        'light-speed-out': 'lightSpeedOut 0.5s ease-out',
        'swing': 'swing 1s ease-in-out',
        'bounce-in-up': 'bounceInUp 0.6s ease-out',
        'bounce-in-down': 'bounceInDown 0.6s ease-out',
        'bounce-in-left': 'bounceInLeft 0.6s ease-out',
        'bounce-in-right': 'bounceInRight 0.6s ease-out',
        'fade-in-up': 'fadeInUp 0.6s ease-out',
        'fade-in-down': 'fadeInDown 0.6s ease-out',
        'fade-in-left': 'fadeInLeft 0.6s ease-out',
        'fade-in-right': 'fadeInRight 0.6s ease-out',
        'slide-in-up': 'slideInUp 0.3s ease-out',
        'slide-in-down': 'slideInDown 0.3s ease-out',
        'slide-in-left': 'slideInLeft 0.3s ease-out',
        'slide-in-right': 'slideInRight 0.3s ease-out',
      },
      keyframes: {
        fadeIn: {
          '0%': { opacity: '0' },
          '100%': { opacity: '1' },
        },
        fadeOut: {
          '0%': { opacity: '1' },
          '100%': { opacity: '0' },
        },
        slideInFromTop: {
          '0%': { transform: 'translateY(-100%)' },
          '100%': { transform: 'translateY(0)' },
        },
        slideInFromBottom: {
          '0%': { transform: 'translateY(100%)' },
          '100%': { transform: 'translateY(0)' },
        },
        slideInFromLeft: {
          '0%': { transform: 'translateX(-100%)' },
          '100%': { transform: 'translateX(0)' },
        },
        slideInFromRight: {
          '0%': { transform: 'translateX(100%)' },
          '100%': { transform: 'translateX(0)' },
        },
        scaleIn: {
          '0%': { transform: 'scale(0.9)', opacity: '0' },
          '100%': { transform: 'scale(1)', opacity: '1' },
        },
        scaleOut: {
          '0%': { transform: 'scale(1)', opacity: '1' },
          '100%': { transform: 'scale(0.9)', opacity: '0' },
        },
        bounceIn: {
          '0%': { transform: 'scale(0.3)', opacity: '0' },
          '50%': { transform: 'scale(1.05)' },
          '70%': { transform: 'scale(0.9)' },
          '100%': { transform: 'scale(1)', opacity: '1' },
        },
        float: {
          '0%, 100%': { transform: 'translateY(0px)' },
          '50%': { transform: 'translateY(-10px)' },
        },
        glow: {
          '0%': { boxShadow: '0 0 5px rgba(59, 130, 246, 0.5)' },
          '100%': { boxShadow: '0 0 20px rgba(59, 130, 246, 0.8)' },
        },
        shimmer: {
          '0%': { transform: 'translateX(-100%)' },
          '100%': { transform: 'translateX(100%)' },
        },
        gradient: {
          '0%, 100%': { backgroundPosition: '0% 50%' },
          '50%': { backgroundPosition: '100% 50%' },
        },
        wiggle: {
          '0%, 100%': { transform: 'rotate(-3deg)' },
          '50%': { transform: 'rotate(3deg)' },
        },
        heartbeat: {
          '0%, 100%': { transform: 'scale(1)' },
          '50%': { transform: 'scale(1.1)' },
        },
        rubberBand: {
          '0%': { transform: 'scale(1)' },
          '30%': { transform: 'scaleX(1.25) scaleY(0.75)' },
          '40%': { transform: 'scaleX(0.75) scaleY(1.25)' },
          '60%': { transform: 'scaleX(1.15) scaleY(0.85)' },
          '100%': { transform: 'scale(1)' },
        },
        shake: {
          '0%, 100%': { transform: 'translateX(0)' },
          '10%, 30%, 50%, 70%, 90%': { transform: 'translateX(-5px)' },
          '20%, 40%, 60%, 80%': { transform: 'translateX(5px)' },
        },
        tada: {
          '0%': { transform: 'scale(1)' },
          '10%, 20%': { transform: 'scale(0.9) rotate(-3deg)' },
          '30%, 50%, 70%, 90%': { transform: 'scale(1.1) rotate(3deg)' },
          '40%, 60%, 80%': { transform: 'scale(1.1) rotate(-3deg)' },
          '100%': { transform: 'scale(1) rotate(0)' },
        },
        wobble: {
          '0%': { transform: 'translateX(0%)' },
          '15%': { transform: 'translateX(-25%) rotate(-5deg)' },
          '30%': { transform: 'translateX(20%) rotate(3deg)' },
          '45%': { transform: 'translateX(-15%) rotate(-3deg)' },
          '60%': { transform: 'translateX(10%) rotate(2deg)' },
          '75%': { transform: 'translateX(-5%) rotate(-1deg)' },
          '100%': { transform: 'translateX(0%)' },
        },
        jello: {
          '0%, 100%': { transform: 'skew(0deg 0deg)' },
          '30%': { transform: 'skew(25deg 25deg)' },
          '40%': { transform: 'skew(-15deg, -15deg)' },
          '50%': { transform: 'skew(15deg, 15deg)' },
          '65%': { transform: 'skew(-5deg, -5deg)' },
          '75%': { transform: 'skew(5deg, 5deg)' },
          '100%': { transform: 'skew(0deg 0deg)' },
        },
        hinge: {
          '0%': { transform: 'rotate(0deg)', transformOrigin: 'top left' },
          '20%, 60%': { transform: 'rotate(80deg)', transformOrigin: 'top left' },
          '40%': { transform: 'rotate(60deg)', transformOrigin: 'top left' },
          '80%': { transform: 'rotate(60deg) translateY(0)', transformOrigin: 'top left' },
          '100%': { transform: 'translateY(700px)' },
        },
        rollIn: {
          '0%': { transform: 'translateX(-100%) rotate(-120deg)', opacity: '0' },
          '100%': { transform: 'translateX(0px) rotate(0deg)', opacity: '1' },
        },
        rollOut: {
          '0%': { transform: 'translateX(0px) rotate(0deg)', opacity: '1' },
          '100%': { transform: 'translateX(100%) rotate(120deg)', opacity: '0' },
        },
        zoomIn: {
          '0%': { transform: 'scale(0.3)', opacity: '0' },
          '50%': { opacity: '1' },
          '100%': { transform: 'scale(1)', opacity: '1' },
        },
        zoomOut: {
          '0%': { transform: 'scale(1)', opacity: '1' },
          '50%': { opacity: '1' },
          '100%': { transform: 'scale(0.3)', opacity: '0' },
        },
        flipInX: {
          '0%': { transform: 'perspective(400px) rotateX(90deg)', opacity: '0' },
          '40%': { transform: 'perspective(400px) rotateX(-20deg)' },
          '60%': { transform: 'perspective(400px) rotateX(10deg)' },
          '80%': { transform: 'perspective(400px) rotateX(-5deg)' },
          '100%': { transform: 'perspective(400px) rotateX(0deg)', opacity: '1' },
        },
        flipInY: {
          '0%': { transform: 'perspective(400px) rotateY(90deg)', opacity: '0' },
          '40%': { transform: 'perspective(400px) rotateY(-20deg)' },
          '60%': { transform: 'perspective(400px) rotateY(10deg)' },
          '80%': { transform: 'perspective(400px) rotateY(-5deg)' },
          '100%': { transform: 'perspective(400px) rotateY(0deg)', opacity: '1' },
        },
        flipOutX: {
          '0%': { transform: 'perspective(400px) rotateX(0deg)', opacity: '1' },
          '100%': { transform: 'perspective(400px) rotateX(90deg)', opacity: '0' },
        },
        flipOutY: {
          '0%': { transform: 'perspective(400px) rotateY(0deg)', opacity: '1' },
          '100%': { transform: 'perspective(400px) rotateY(90deg)', opacity: '0' },
        },
        lightSpeedIn: {
          '0%': { transform: 'translateX(-100%) skewX(30deg)', opacity: '0' },
          '60%': { transform: 'skewX(-20deg)' },
          '80%': { transform: 'skewX(5deg)' },
          '100%': { transform: 'translateX(0%) skewX(0deg)', opacity: '1' },
        },
        lightSpeedOut: {
          '0%': { transform: 'translateX(0%) skewX(0deg)', opacity: '1' },
          '100%': { transform: 'translateX(100%) skewX(-30deg)', opacity: '0' },
        },
        swing: {
          '20%': { transform: 'rotate(15deg)' },
          '40%': { transform: 'rotate(-10deg)' },
          '60%': { transform: 'rotate(5deg)' },
          '80%': { transform: 'rotate(-5deg)' },
          '100%': { transform: 'rotate(0deg)' },
        },
        bounceInUp: {
          '0%': { transform: 'translateY(300px)', opacity: '0' },
          '60%': { transform: 'translateY(-20px)' },
          '80%': { transform: 'translateY(10px)' },
          '100%': { transform: 'translateY(0)', opacity: '1' },
        },
        bounceInDown: {
          '0%': { transform: 'translateY(-300px)', opacity: '0' },
          '60%': { transform: 'translateY(20px)' },
          '80%': { transform: 'translateY(-10px)' },
          '100%': { transform: 'translateY(0)', opacity: '1' },
        },
        bounceInLeft: {
          '0%': { transform: 'translateX(-300px)', opacity: '0' },
          '60%': { transform: 'translateX(20px)' },
          '80%': { transform: 'translateX(-10px)' },
          '100%': { transform: 'translateX(0)', opacity: '1' },
        },
        bounceInRight: {
          '0%': { transform: 'translateX(300px)', opacity: '0' },
          '60%': { transform: 'translateX(-20px)' },
          '80%': { transform: 'translateX(10px)' },
          '100%': { transform: 'translateX(0)', opacity: '1' },
        },
        fadeInUp: {
          '0%': { transform: 'translateY(30px)', opacity: '0' },
          '100%': { transform: 'translateY(0)', opacity: '1' },
        },
        fadeInDown: {
          '0%': { transform: 'translateY(-30px)', opacity: '0' },
          '100%': { transform: 'translateY(0)', opacity: '1' },
        },
        fadeInLeft: {
          '0%': { transform: 'translateX(-30px)', opacity: '0' },
          '100%': { transform: 'translateX(0)', opacity: '1' },
        },
        fadeInRight: {
          '0%': { transform: 'translateX(30px)', opacity: '0' },
          '100%': { transform: 'translateX(0)', opacity: '1' },
        },
        slideInUp: {
          '0%': { transform: 'translateY(100%)' },
          '100%': { transform: 'translateY(0)' },
        },
        slideInDown: {
          '0%': { transform: 'translateY(-100%)' },
          '100%': { transform: 'translateY(0)' },
        },
        slideInLeft: {
          '0%': { transform: 'translateX(-100%)' },
          '100%': { transform: 'translateX(0)' },
        },
        slideInRight: {
          '0%': { transform: 'translateX(100%)' },
          '100%': { transform: 'translateX(0)' },
        },
      },
      backdropBlur: {
        xs: '2px',
      },
      boxShadow: {
        'soft': '0 2px 15px -3px rgba(0, 0, 0, 0.07), 0 10px 20px -2px rgba(0, 0, 0, 0.04)',
        'medium': '0 4px 25px -5px rgba(0, 0, 0, 0.1), 0 10px 10px -5px rgba(0, 0, 0, 0.04)',
        'strong': '0 10px 40px -10px rgba(0, 0, 0, 0.15), 0 2px 10px -2px rgba(0, 0, 0, 0.05)',
        'glow': '0 0 20px rgba(59, 130, 246, 0.3)',
        'glow-lg': '0 0 40px rgba(59, 130, 246, 0.4)',
        'inner-soft': 'inset 0 2px 4px 0 rgba(0, 0, 0, 0.06)',
        'inner-medium': 'inset 0 4px 8px 0 rgba(0, 0, 0, 0.1)',
      },
    },
  },
  plugins: [],
} 